export interface DevnetEnvironment {
  adminToken: string;
  operatorSeed: string;
  operatorSecret: string;
  operatorAuthority: string;
  sentinelAddress: string;
  sponsorDustAddress: string;
}

export const renderDevnetEnvironment = (value: DevnetEnvironment): string =>
  [
    '# Generated by pnpm --filter @midnight-sentinel/sponsor-service setup:devnet',
    '# Local devnet only. Do not reuse these credentials on another network.',
    'SERVICE_HOST=127.0.0.1',
    'SERVICE_PORT=8089',
    'SERVICE_DB_PATH=./sponsor-service.sqlite',
    `SERVICE_ADMIN_TOKEN=${value.adminToken}`,
    `SERVICE_OPERATOR_SEED=${value.operatorSeed}`,
    `SERVICE_OPERATOR_SECRET=${value.operatorSecret}`,
    `SERVICE_PRIVATE_STATE_STORE=eligibility-operator-${value.sentinelAddress.slice(0, 12)}`,
    'SERVICE_REVALIDATE_MS=15000',
    'SERVICE_LOG_DIR=./logs/sponsor-service',
    'SERVICE_ZK_CONFIG_PATH=../../packages/contract/dist/managed/sentinel',
    'MIDNIGHT_NETWORK=undeployed',
    'MIDNIGHT_INDEXER_HTTP=http://127.0.0.1:8088/api/v4/graphql',
    'MIDNIGHT_INDEXER_WS=ws://127.0.0.1:8088/api/v4/graphql/ws',
    'MIDNIGHT_NODE=http://127.0.0.1:9944',
    'MIDNIGHT_PROOF_SERVER=http://127.0.0.1:6300',
    `SENTINEL_ADDRESS=${value.sentinelAddress}`,
    `SPONSOR_DUST_ADDRESS=${value.sponsorDustAddress}`,
    `EXPECTED_OPERATOR_AUTHORITY=${value.operatorAuthority}`,
    '',
  ].join('\n');
