import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { access, mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ContractCall, PreProof, shieldedToken, unshieldedToken } from '@midnight-ntwrk/ledger-v8';
import { createUnprovenCallTx, deployContract } from '@midnight-ntwrk/midnight-js-contracts';
import {
  DustAddress,
  MidnightBech32m,
  UnshieldedAddress,
} from '@midnight-ntwrk/wallet-sdk-address-format';
import { SentinelContract } from '@midnight-sentinel/api';
import {
  createMidnightEnrollmentVerifier,
  createHttpMidnightRegistrationProvider,
  enrollmentIdentity,
  enrollmentSigningBytes,
  type EnrollmentPayload,
  type SignedEnrollment,
} from '@midnight-sentinel/api/sponsorship/eligibility';
import {
  createMidnightBeneficiarySponsorshipApi,
  createMidnightSponsorSponsorshipApi,
  createMidnightSponsorshipTarget,
  dustPublicKeyToBytes,
  nativeNightSponsorshipConfig,
} from '@midnight-sentinel/api/sponsorship/midnight';
import {
  sponsorshipAllowlistHash,
  type SponsorshipPolicy,
} from '@midnight-sentinel/api/sponsorship';
import {
  createPrivateState,
  deriveSentinelAuthority,
  ledger as sentinelLedger,
  sentinelContractPrivateStateKey,
} from '@midnight-sentinel/contract';
import { configureProviders } from '@midnight-sentinel/contract/providers';
import {
  CompositeTargetCompiledContract,
  compositeTargetLedger,
  type CompositeTargetContractType,
} from '@midnight-sentinel/protocol-verification/composite-sponsorship';
import {
  buildUnfundedWallet,
  buildWallet,
  getBalancesAndAddresses,
  type WalletContext,
} from '@midnight-sentinel/wallet';
import * as Rx from 'rxjs';
import { loadConfig } from '../config.js';
import { EligibilityDatabase } from '../database.js';
import { MidnightIndexerScanner } from '../indexer.js';
import { ContractQueueOperator } from '../operator.js';
import { buildServer } from '../server.js';
import { EligibilityService } from '../service.js';

const GENESIS_DEPLOYER_SEED = `${'0'.repeat(63)}1`;
const GENESIS_OPERATOR_SEED = `${'0'.repeat(63)}2`;
const GENESIS_SPONSOR_SEED = `${'0'.repeat(63)}3`;
const NETWORK = 'undeployed';
const INDEXER = 'http://127.0.0.1:8088/api/v4/graphql';
const INDEXER_WS = 'ws://127.0.0.1:8088/api/v4/graphql/ws';
const NODE = 'http://127.0.0.1:9944';
const PROOF_SERVER = 'http://127.0.0.1:6300';
const SHARE = 1n;
const PRICE = 2n;
// Registration is self-funded from DUST generated by the NIGHT being
// registered. Tiny ledger values are useful for contract simulation but do not
// generate a real devnet registration fee in a practical amount of time.
const MINIMUM = 10_000_000_000_000n;
const TTL = () => new Date(Date.now() + 30 * 60_000);
const TIMEOUT = 8 * 60_000;

const packageDirectory = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const repositoryDirectory = path.resolve(packageDirectory, '../..');
const sentinelZkPath = path.join(repositoryDirectory, 'packages/contract/dist/managed/sentinel');
const targetZkPath = path.join(
  repositoryDirectory,
  'packages/protocol-verification/dist/managed/composite-target'
);

const config = {
  networkId: NETWORK,
  indexer: INDEXER,
  indexerWS: INDEXER_WS,
  node: NODE,
  proofServer: PROOF_SERVER,
  privateStateStoreName: 'devnet-e2e',
  logDir: path.join(packageDirectory, 'logs/devnet-e2e'),
  zkConfigPath: sentinelZkPath,
  eligibilityService: '',
};

type SyncedState = Awaited<ReturnType<typeof syncedState>>;
type ScenarioResult = { name: string; status: 'passed' | 'failed'; detail?: unknown };

class TerminalWaitError extends Error {}

const report: {
  runId: string;
  startedAt: string;
  verdict: string;
  stage: string;
  baseline?: unknown;
  funding?: unknown;
  contracts?: unknown;
  final?: unknown;
  scenarios: ScenarioResult[];
  transactions: Record<string, string>;
  finishedAt?: string;
  error?: string;
} = {
  runId: randomBytes(8).toString('hex'),
  startedAt: new Date().toISOString(),
  verdict: 'inconclusive',
  stage: 'preflight',
  scenarios: [],
  transactions: {},
};

const withTimeout = async <T>(label: string, promise: Promise<T>): Promise<T> => {
  let timer: NodeJS.Timeout | undefined;
  try {
    return await Promise.race([
      promise,
      new Promise<never>((_, reject) => {
        timer = setTimeout(() => reject(new Error(`${label} timed out`)), TIMEOUT);
      }),
    ]);
  } finally {
    if (timer) clearTimeout(timer);
  }
};

const syncedState = (ctx: WalletContext) =>
  withTimeout(
    'wallet synchronization',
    Rx.firstValueFrom(ctx.wallet.state().pipe(Rx.filter((state) => state.isSynced)))
  );

const waitForState = <T>(
  label: string,
  ctx: WalletContext,
  predicate: (state: SyncedState) => T | false
) =>
  withTimeout(
    label,
    Rx.firstValueFrom(
      ctx.wallet.state().pipe(
        Rx.filter((state) => state.isSynced),
        Rx.map(predicate),
        Rx.filter((value): value is T => value !== false)
      )
    )
  );

const waitFor = async <T>(
  label: string,
  action: () => Promise<T | false>,
  timeout = TIMEOUT
): Promise<T> => {
  const started = Date.now();
  let lastProgress = started;
  let lastError: unknown;
  while (Date.now() - started < timeout) {
    try {
      const value = await action();
      if (value !== false) return value;
    } catch (error) {
      if (error instanceof TerminalWaitError) throw error;
      lastError = error;
    }
    if (Date.now() - lastProgress >= 15_000) {
      console.log(
        JSON.stringify({
          waiting: label,
          elapsedSeconds: Math.floor((Date.now() - started) / 1_000),
        })
      );
      lastProgress = Date.now();
    }
    await new Promise((resolve) => setTimeout(resolve, 1_000));
  }
  throw new Error(`${label} timed out${lastError ? `: ${String(lastError)}` : ''}`);
};

const scenario = async (name: string, action: () => Promise<unknown>) => {
  try {
    const detail = await action();
    report.scenarios.push({ name, status: 'passed', detail });
    console.log(JSON.stringify({ scenario: name, status: 'passed' }));
    return detail;
  } catch (error) {
    report.scenarios.push({
      name,
      status: 'failed',
      detail: error instanceof Error ? error.message : String(error),
    });
    throw error;
  }
};

const graphql = async (query: string) => {
  const response = await fetch(INDEXER, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ query }),
  });
  assert(response.ok, `indexer returned HTTP ${response.status}`);
  const result = (await response.json()) as { data?: unknown; errors?: unknown };
  assert(!result.errors, `indexer GraphQL error: ${JSON.stringify(result.errors)}`);
  return result.data;
};

const nodeRpc = async (method: string) => {
  const response = await fetch(NODE, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ jsonrpc: '2.0', id: 1, method, params: [] }),
  });
  assert(response.ok, `node returned HTTP ${response.status}`);
  const result = (await response.json()) as { result?: unknown; error?: unknown };
  assert(!result.error, `node RPC error: ${JSON.stringify(result.error)}`);
  return result.result;
};

const preflight = async () => {
  await Promise.all([
    access(path.join(sentinelZkPath, 'keys/purchaseSponsorship.prover')),
    access(path.join(targetZkPath, 'keys/interact.prover')),
  ]);
  const [health, version, block, proof] = await Promise.all([
    nodeRpc('system_health'),
    nodeRpc('system_version'),
    graphql('{ block { height } }'),
    fetch(`${PROOF_SERVER}/health`).catch(() => fetch(PROOF_SERVER)),
  ]);
  assert(proof.ok, `proof server returned HTTP ${proof.status}`);
  return { network: NETWORK, nodeVersion: version, nodeHealth: health, indexer: block };
};

const addresses = (ctx: WalletContext, seed: string) => getBalancesAndAddresses(ctx.wallet, seed);

const walletSnapshot = async (ctx: WalletContext, seed: string) => {
  const value = await addresses(ctx, seed);
  return {
    addresses: value.addresses,
    balances: {
      dust: value.balances.dust.toString(),
      shieldedNight: (value.balances.shielded[shieldedToken().raw] ?? 0n).toString(),
      unshieldedNight: (value.balances.unshielded[unshieldedToken().raw] ?? 0n).toString(),
    },
  };
};

const decodeUnshielded = (address: string) =>
  UnshieldedAddress.codec.decode(NETWORK, MidnightBech32m.parse(address));

const decodeDust = (address: string) =>
  DustAddress.codec.decode(NETWORK, MidnightBech32m.parse(address));

const submitRecipe = async (
  wallet: WalletContext,
  recipe: Awaited<ReturnType<WalletContext['wallet']['transferTransaction']>>
) => {
  const signed = await wallet.wallet.signRecipe(recipe, (payload) =>
    wallet.unshieldedKeystore.signData(payload)
  );
  const finalized = await wallet.wallet.finalizeRecipe(signed);
  return wallet.wallet.submitTransaction(finalized);
};

const fundUnshielded = async (
  funder: WalletContext,
  recipients: Array<{ address: string; amount: bigint }>
) => {
  const recipe = await funder.wallet.transferTransaction(
    [
      {
        type: 'unshielded',
        outputs: recipients.map(({ address, amount }) => ({
          type: unshieldedToken().raw,
          amount,
          receiverAddress: decodeUnshielded(address),
        })),
      },
    ],
    {
      shieldedSecretKeys: funder.shieldedSecretKeys,
      dustSecretKey: funder.dustSecretKey,
    },
    { ttl: TTL() }
  );
  return submitRecipe(funder, recipe);
};

const fundShielded = async (funder: WalletContext, recipient: string, amounts: bigint[]) => {
  const state = await syncedState(funder);
  void state;
  const { ShieldedAddress } = await import('@midnight-ntwrk/wallet-sdk-address-format');
  const decoded = ShieldedAddress.codec.decode(NETWORK, MidnightBech32m.parse(recipient));
  const recipe = await funder.wallet.transferTransaction(
    [
      {
        type: 'shielded',
        outputs: amounts.map((amount) => ({
          type: shieldedToken().raw,
          amount,
          receiverAddress: decoded,
        })),
      },
    ],
    {
      shieldedSecretKeys: funder.shieldedSecretKeys,
      dustSecretKey: funder.dustSecretKey,
    },
    { ttl: TTL() }
  );
  return submitRecipe(funder, recipe);
};

const registerWithSponsor = async (delegator: WalletContext, sponsorDustAddress: string) => {
  const state = await syncedState(delegator);
  const coins = state.unshielded.availableCoins.filter(
    (coin) => coin.meta?.registeredForDustGeneration !== true
  );
  assert(coins.length > 0, 'delegator has no unregistered NIGHT UTXOs');
  const readiness = await waitFor('registration DUST generation', async () => {
    const estimate = await delegator.wallet.estimateRegistration(coins);
    const generated = estimate.dustGenerationEstimations.reduce(
      (total, value) => total + value.dust.generatedNow,
      0n
    );
    return generated >= estimate.fee ? { fee: estimate.fee, generated } : false;
  });
  console.log(
    JSON.stringify({
      registrationReady: true,
      fee: readiness.fee.toString(),
      generatedDust: readiness.generated.toString(),
    })
  );
  const recipe = await delegator.wallet.registerNightUtxosForDustGeneration(
    coins,
    delegator.unshieldedKeystore.getPublicKey(),
    (payload) => delegator.unshieldedKeystore.signData(payload),
    decodeDust(sponsorDustAddress)
  );
  const finalized = await delegator.wallet.finalizeRecipe(recipe);
  return delegator.wallet.submitTransaction(finalized);
};

const deregisterNight = async (delegator: WalletContext) => {
  const state = await syncedState(delegator);
  const coins = state.unshielded.availableCoins.filter(
    (coin) => coin.meta?.registeredForDustGeneration === true
  );
  assert(coins.length > 0, 'delegator has no registered NIGHT UTXOs');
  const recipe = await delegator.wallet.deregisterFromDustGeneration(
    coins,
    delegator.unshieldedKeystore.getPublicKey(),
    (payload) => delegator.unshieldedKeystore.signData(payload)
  );
  const finalized = await delegator.wallet.finalizeRecipe(recipe);
  return delegator.wallet.submitTransaction(finalized);
};

const makeEnrollment = async (
  wallet: WalletContext,
  seed: string,
  sentinelAddress: string,
  sponsorDustAddress: string,
  nonce = 1n,
  expiresAt = new Date(Date.now() + 60 * 60_000)
): Promise<SignedEnrollment> => {
  const { addresses: walletAddresses } = await addresses(wallet, seed);
  const payload: EnrollmentPayload = {
    version: 1,
    network: NETWORK,
    sentinelAddress,
    sponsorDustAddress,
    nightRewardAddress: walletAddresses.unshielded,
    nightVerificationKey: wallet.unshieldedKeystore.getPublicKey(),
    shieldedCoinPublicKey: wallet.shieldedSecretKeys.coinPublicKey,
    shieldedEncryptionPublicKey: wallet.shieldedSecretKeys.encryptionPublicKey,
    nonce: nonce.toString(),
    expiresAt: expiresAt.toISOString(),
  };
  return {
    payload,
    signature: wallet.unshieldedKeystore.signData(enrollmentSigningBytes(payload)),
  };
};

const postEnrollment = async (baseUrl: string, enrollment: SignedEnrollment) =>
  fetch(`${baseUrl}/v1/enrollments`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify(enrollment),
  });

const waitForJob = async (baseUrl: string, id: string, expected: 'active' | 'ineligible') =>
  waitFor(`eligibility job ${id}`, async () => {
    const response = await fetch(`${baseUrl}/v1/jobs/${id}`);
    if (!response.ok) return false;
    const job = (await response.json()) as { status: string; errorCode?: string };
    if (job.status === 'failed') {
      throw new TerminalWaitError(`eligibility job failed: ${job.errorCode}`);
    }
    if (job.status === 'ineligible' && expected !== 'ineligible') {
      throw new TerminalWaitError(`eligibility job became ineligible: ${job.errorCode}`);
    }
    return job.status === expected ? job : false;
  });

const bytes32 = (value: number) => new Uint8Array(32).fill(value);

const main = async () => {
  const wallets: WalletContext[] = [];
  let database: EligibilityDatabase | undefined;
  let service: EligibilityService | undefined;
  let server: Awaited<ReturnType<typeof buildServer>> | undefined;
  const runDirectory = await mkdtemp(path.join(tmpdir(), `sentinel-e2e-${report.runId}-`));
  const reportPath = path.join(runDirectory, 'report.json');

  try {
    report.baseline = await preflight();
    report.stage = 'wallet-initialization';

    const seeds = {
      beneficiary: randomBytes(32).toString('hex'),
      eligible: Array.from({ length: 3 }, () => randomBytes(32).toString('hex')),
      unregistered: randomBytes(32).toString('hex'),
      belowMinimum: randomBytes(32).toString('hex'),
    };
    const [deployer, sponsor, operator, beneficiary, ...delegators] = await Promise.all([
      buildWallet(config, GENESIS_DEPLOYER_SEED),
      buildWallet(config, GENESIS_SPONSOR_SEED),
      buildWallet(config, GENESIS_OPERATOR_SEED),
      buildUnfundedWallet(config, seeds.beneficiary),
      ...seeds.eligible.map((seed) => buildUnfundedWallet(config, seed)),
      buildUnfundedWallet(config, seeds.unregistered),
      buildUnfundedWallet(config, seeds.belowMinimum),
    ]);
    wallets.push(deployer, sponsor, operator, beneficiary, ...delegators);
    const eligible = delegators.slice(0, 3);
    const unregistered = delegators[3]!;
    const belowMinimum = delegators[4]!;
    report.baseline = {
      ...(report.baseline as object),
      wallets: {
        deployer: await walletSnapshot(deployer, GENESIS_DEPLOYER_SEED),
        sponsor: await walletSnapshot(sponsor, GENESIS_SPONSOR_SEED),
        operator: await walletSnapshot(operator, GENESIS_OPERATOR_SEED),
        beneficiary: await walletSnapshot(beneficiary, seeds.beneficiary),
        eligible: await Promise.all(
          eligible.map((wallet, index) => walletSnapshot(wallet, seeds.eligible[index]!))
        ),
        unregistered: await walletSnapshot(unregistered, seeds.unregistered),
        belowMinimum: await walletSnapshot(belowMinimum, seeds.belowMinimum),
      },
    };

    const delegatorAddresses = await Promise.all(
      eligible.map((wallet, index) => addresses(wallet, seeds.eligible[index]!))
    );
    const belowAddress = await addresses(belowMinimum, seeds.belowMinimum);
    const requiredUnshieldedFunding = MINIMUM * 2n * BigInt(eligible.length) + MINIMUM - 1n;
    const fundingCandidates = await Promise.all(
      [
        { name: 'deployer', wallet: deployer },
        { name: 'sponsor', wallet: sponsor },
        { name: 'operator', wallet: operator },
      ].map(async (candidate) => ({
        ...candidate,
        balance:
          (await syncedState(candidate.wallet)).unshielded.balances[unshieldedToken().raw] ?? 0n,
      }))
    );
    const nightFunder = fundingCandidates
      .sort((left, right) =>
        left.balance > right.balance ? -1 : left.balance < right.balance ? 1 : 0
      )
      .find(({ balance }) => balance >= requiredUnshieldedFunding);
    assert(
      nightFunder,
      `devnet genesis wallets lack the ${requiredUnshieldedFunding} unshielded NIGHT required by the E2E run; reset the devnet`
    );
    report.funding = {
      source: nightFunder.name,
      available: nightFunder.balance.toString(),
      required: requiredUnshieldedFunding.toString(),
    };
    report.stage = 'unshielded-funding';
    report.transactions.fundUnshielded = await fundUnshielded(nightFunder.wallet, [
      ...delegatorAddresses.map(({ addresses: value }) => ({
        address: value.unshielded,
        amount: MINIMUM * 2n,
      })),
      { address: belowAddress.addresses.unshielded, amount: MINIMUM - 1n },
    ]);
    await Promise.all([
      ...eligible.map((wallet) =>
        waitForState('delegator NIGHT funding', wallet, (state) =>
          (state.unshielded.balances[unshieldedToken().raw] ?? 0n) >= MINIMUM ? state : false
        )
      ),
      waitForState('below-minimum NIGHT funding', belowMinimum, (state) =>
        (state.unshielded.balances[unshieldedToken().raw] ?? 0n) === MINIMUM - 1n ? state : false
      ),
    ]);

    const sponsorAddresses = await addresses(sponsor, GENESIS_SPONSOR_SEED);
    report.stage = 'dust-registration';
    const registrationWallets = [...eligible, belowMinimum];
    for (let index = 0; index < registrationWallets.length; index += 1) {
      report.stage = `dust-registration-${index + 1}`;
      report.transactions[`registration${index + 1}`] = await registerWithSponsor(
        registrationWallets[index]!,
        sponsorAddresses.addresses.dust
      );
    }

    report.stage = 'contract-deployment';
    const deployTargetProviders = await configureProviders(
      deployer,
      config,
      path.join(runDirectory, 'target-deploy'),
      targetZkPath
    );
    const targetDeployment = await deployContract<CompositeTargetContractType>(
      deployTargetProviders as never,
      { compiledContract: CompositeTargetCompiledContract } as never
    );
    const targetAddress = targetDeployment.deployTxData.public.contractAddress;
    const allowedTargets = [{ address: targetAddress, entryPoint: 'interact' }];
    const policyHash = sponsorshipAllowlistHash(allowedTargets);
    const operatorSecret = Uint8Array.from(randomBytes(32));
    const operatorAuthority = deriveSentinelAuthority(operatorSecret);
    const sentinelDeployProviders = await configureProviders(
      deployer,
      config,
      path.join(runDirectory, 'sentinel-deploy'),
      sentinelZkPath
    );
    const deployedSentinel = await SentinelContract.deploy(
      sentinelDeployProviders,
      nativeNightSponsorshipConfig(sponsor, policyHash, {
        sponsorShare: SHARE,
        delegatorShare: SHARE,
        minimumRegisteredNight: MINIMUM,
        initialEligibilityOperator: operatorAuthority,
      })
    );
    const sentinelAddress = deployedSentinel.deployedContract!.deployTxData.public.contractAddress;
    report.contracts = { sentinelAddress, targetAddress };

    const initialState = await deployedSentinel.readState();
    assert.equal(initialState.delegatorCount, 0n);
    assert.equal(initialState.rewardCursor, 0n);
    assert.equal(initialState.sponsorshipPurchases, 0n);
    assert.equal(initialState.sponsorshipFixedPrice, PRICE);
    assert.equal(initialState.sponsorshipMinimumRegisteredNight, MINIMUM);

    const operatorProviders = await configureProviders(
      operator,
      config,
      path.join(runDirectory, 'operator'),
      sentinelZkPath
    );
    operatorProviders.privateStateProvider.setContractAddress(sentinelAddress);
    await operatorProviders.privateStateProvider.set(
      sentinelContractPrivateStateKey,
      createPrivateState(operatorSecret)
    );
    const operatorContract = await SentinelContract.join(operatorProviders, sentinelAddress);

    const serviceConfig = loadConfig({
      SERVICE_HOST: '127.0.0.1',
      SERVICE_PORT: '8089',
      SERVICE_DB_PATH: path.join(runDirectory, 'eligibility.sqlite'),
      SERVICE_ADMIN_TOKEN: randomBytes(32).toString('hex'),
      SERVICE_OPERATOR_SEED: GENESIS_OPERATOR_SEED,
      SERVICE_OPERATOR_SECRET: Buffer.from(operatorSecret).toString('hex'),
      SERVICE_PRIVATE_STATE_STORE: path.join(runDirectory, 'operator-service'),
      SERVICE_REVALIDATE_MS: '1000',
      SERVICE_LOG_DIR: path.join(runDirectory, 'logs'),
      SERVICE_ZK_CONFIG_PATH: sentinelZkPath,
      MIDNIGHT_NETWORK: NETWORK,
      MIDNIGHT_INDEXER_HTTP: INDEXER,
      MIDNIGHT_INDEXER_WS: INDEXER_WS,
      MIDNIGHT_NODE: NODE,
      MIDNIGHT_PROOF_SERVER: PROOF_SERVER,
      SENTINEL_ADDRESS: sentinelAddress,
      SPONSOR_DUST_ADDRESS: sponsorAddresses.addresses.dust,
      EXPECTED_OPERATOR_AUTHORITY: Buffer.from(operatorAuthority).toString('hex'),
    });
    database = new EligibilityDatabase(serviceConfig.dbPath);
    const sponsorDustKey = decodeDust(sponsorAddresses.addresses.dust).data;
    const scanner = new MidnightIndexerScanner(
      INDEXER,
      INDEXER_WS,
      database,
      sponsorDustKey.toString()
    );
    service = new EligibilityService(
      database,
      scanner,
      new ContractQueueOperator(operatorContract),
      {
        network: NETWORK,
        sentinelAddress,
        sponsorDustAddress: sponsorAddresses.addresses.dust,
        minimumRegisteredNight: MINIMUM,
      },
      createMidnightEnrollmentVerifier(NETWORK),
      1_000
    );
    server = buildServer(serviceConfig, service);
    service.start();
    report.stage = 'service-startup';
    const baseUrl = await server.listen({ host: '127.0.0.1', port: 0 });
    const ready = await fetch(`${baseUrl}/readyz`);
    assert.equal(ready.status, 200);

    report.stage = 'beneficiary-funding';
    const beneficiaryAddresses = await addresses(beneficiary, seeds.beneficiary);
    report.transactions.fundBeneficiary = await fundShielded(
      deployer,
      beneficiaryAddresses.addresses.shielded,
      Array.from({ length: 6 }, () => PRICE)
    );
    await waitForState('beneficiary shielded funding', beneficiary, (state) =>
      (state.shielded.balances[shieldedToken().raw] ?? 0n) >= PRICE * 6n ? state : false
    );

    const beneficiarySentinelProviders = await configureProviders(
      beneficiary,
      config,
      path.join(runDirectory, 'beneficiary-sentinel'),
      sentinelZkPath
    );
    await SentinelContract.join(beneficiarySentinelProviders, sentinelAddress);
    const beneficiaryTargetProviders = await configureProviders(
      beneficiary,
      config,
      path.join(runDirectory, 'beneficiary-target'),
      targetZkPath
    );
    const sponsorProviders = await configureProviders(
      sponsor,
      config,
      path.join(runDirectory, 'sponsor'),
      sentinelZkPath
    );

    const beneficiaryApi = createMidnightBeneficiarySponsorshipApi({
      sentinelAddress,
      sentinelProviders: beneficiarySentinelProviders,
      beneficiary,
      proofServer: PROOF_SERVER,
    });
    const policy: SponsorshipPolicy = {
      sentinelAddress,
      sponsorId: dustPublicKeyToBytes(sponsor.dustSecretKey.publicKey),
      sponsorDustAddress: sponsorAddresses.addresses.dust,
      registrationProvider: createHttpMidnightRegistrationProvider(baseUrl),
      policyHash,
      allowedTargets,
      minTtlMs: 0,
      maxTtlMs: 65 * 60_000,
      maxFee: 1_000_000_000_000_000_000n,
    };
    const sponsorApi = createMidnightSponsorSponsorshipApi({
      policy,
      sentinelProviders: sponsorProviders,
      sponsor,
    });

    const targetCall = (expiry: bigint) =>
      createUnprovenCallTx(beneficiaryTargetProviders as never, {
        compiledContract: CompositeTargetCompiledContract as never,
        contractAddress: targetAddress,
        circuitId: 'interact',
        args: [expiry],
      });

    report.stage = 'scenarios';
    await scenario('empty queue rejects sponsorship without state changes', async () => {
      const before = await deployedSentinel.readState();
      const call = await targetCall(BigInt(Math.floor(Date.now() / 1000) + 900));
      const calls = [...(call.private.unprovenTx.intents?.values() ?? [])]
        .flatMap((intent) => intent.actions)
        .filter((action): action is ContractCall<PreProof> => action instanceof ContractCall);
      assert.equal(calls.length, 1);
      await assert.rejects(
        beneficiaryApi.prepare({
          target: createMidnightSponsorshipTarget({
            targetCall: call,
            zkConfigProvider: beneficiaryTargetProviders.zkConfigProvider,
          }),
          expiresAt: TTL(),
          purchaseId: bytes32(0x10),
        }),
        (error: Error & { code?: string }) =>
          error.code === 'NO_ELIGIBLE_DELEGATOR' || error.message.includes('NO_ELIGIBLE_DELEGATOR')
      );
      const after = await deployedSentinel.readState();
      assert.equal(after.sponsorshipPurchases, before.sponsorshipPurchases);
      assert.equal(after.rewardCursor, before.rewardCursor);
      return { purchases: after.sponsorshipPurchases.toString() };
    });

    await scenario('HTTP enrollment defenses', async () => {
      const valid = await makeEnrollment(
        unregistered,
        seeds.unregistered,
        sentinelAddress,
        sponsorAddresses.addresses.dust
      );
      const invalidSignature = await postEnrollment(baseUrl, {
        ...valid,
        signature: valid.signature.replace(/^../, valid.signature.startsWith('00') ? '01' : '00'),
      });
      assert.equal(invalidSignature.status, 400);
      const expired = await makeEnrollment(
        unregistered,
        seeds.unregistered,
        sentinelAddress,
        sponsorAddresses.addresses.dust,
        2n,
        new Date(Date.now() - 1_000)
      );
      assert.equal((await postEnrollment(baseUrl, expired)).status, 400);
      const wrongCampaign = await makeEnrollment(
        unregistered,
        seeds.unregistered,
        'ff'.repeat(32),
        sponsorAddresses.addresses.dust,
        3n
      );
      assert.equal((await postEnrollment(baseUrl, wrongCampaign)).status, 400);
      const accepted = await postEnrollment(baseUrl, valid);
      assert.equal(accepted.status, 202);
      const { jobId } = (await accepted.json()) as { jobId: string };
      await waitForJob(baseUrl, jobId, 'ineligible');
      const unauthorized = await fetch(`${baseUrl}/v1/admin/revalidate`, {
        method: 'POST',
        headers: { 'content-type': 'application/json', authorization: 'Bearer wrong' },
        body: '{}',
      });
      assert.equal(unauthorized.status, 401);
      return { invalidSignature: 400, expired: 400, wrongCampaign: 400, unregistered: 202 };
    });

    const activeEnrollments: SignedEnrollment[] = [];
    await scenario('real indexer enrollment activates three delegators', async () => {
      for (let index = 0; index < eligible.length; index += 1) {
        const enrollment = await makeEnrollment(
          eligible[index]!,
          seeds.eligible[index]!,
          sentinelAddress,
          sponsorAddresses.addresses.dust
        );
        activeEnrollments.push(enrollment);
        const response = await postEnrollment(baseUrl, enrollment);
        assert.equal(response.status, 202);
        const { jobId } = (await response.json()) as { jobId: string };
        await waitForJob(baseUrl, jobId, 'active');
      }
      const state = await waitFor('three on-chain delegators', async () => {
        const current = await deployedSentinel.readState();
        return current.delegatorCount === 3n ? current : false;
      });
      const replay = await postEnrollment(baseUrl, activeEnrollments[0]!);
      assert.equal(replay.status, 400);
      return { delegatorCount: state.delegatorCount.toString(), replayStatus: replay.status };
    });

    await scenario('below-minimum registration is rejected asynchronously', async () => {
      const enrollment = await makeEnrollment(
        belowMinimum,
        seeds.belowMinimum,
        sentinelAddress,
        sponsorAddresses.addresses.dust
      );
      const response = await postEnrollment(baseUrl, enrollment);
      assert.equal(response.status, 202);
      const { jobId } = (await response.json()) as { jobId: string };
      const job = await waitForJob(baseUrl, jobId, 'ineligible');
      assert.equal((await deployedSentinel.readState()).delegatorCount, 3n);
      return job;
    });

    const beforeSponsor = (await syncedState(sponsor)).shielded.balances[shieldedToken().raw] ?? 0n;
    const beforeDelegators = await Promise.all(
      eligible.map(
        async (wallet) => (await syncedState(wallet)).shielded.balances[shieldedToken().raw] ?? 0n
      )
    );

    const purchase = async (index: number, failFallible: boolean) => {
      const expiry = BigInt(Math.floor(Date.now() / 1000) + (failFallible ? 5 : 900));
      const call = await targetCall(expiry);
      const prepared = await beneficiaryApi.prepare({
        target: createMidnightSponsorshipTarget({
          targetCall: call,
          zkConfigProvider: beneficiaryTargetProviders.zkConfigProvider,
        }),
        expiresAt: TTL(),
        purchaseId: bytes32(0x40 + index),
      });
      if (failFallible) {
        await waitFor('target expiry', async () =>
          BigInt(Math.floor(Date.now() / 1000)) > expiry ? true : false
        );
      }
      const submitted = await sponsorApi.sponsorAndSubmit({
        transaction: prepared.transaction,
      });
      report.transactions[`purchase${index}`] = submitted.txId;
      return submitted;
    };

    await scenario(
      'real rewards rotate A-B-C-A across successful and fallible execution',
      async () => {
        const submissions = [];
        submissions.push(await purchase(0, false));
        submissions.push(await purchase(1, true));
        submissions.push(await purchase(2, false));
        submissions.push(await purchase(3, false));
        assert.equal(submissions[0]!.status, 'SucceedEntirely');
        assert.equal(submissions[1]!.status, 'FailFallible');

        const state = await waitFor('four sponsorship receipts', async () => {
          const current = await deployedSentinel.readState();
          return current.sponsorshipPurchases === 4n ? current : false;
        });
        assert.equal(state.sponsorshipReceipts.size(), 4n);
        assert.equal(state.rewardCursor, 1n);

        await waitForState('sponsor rewards', sponsor, (walletState) =>
          (walletState.shielded.balances[shieldedToken().raw] ?? 0n) === beforeSponsor + 3n
            ? walletState
            : false
        );
        const expected = [2n, 1n, 1n];
        await Promise.all(
          eligible.map((wallet, index) =>
            waitForState(`delegator ${index + 1} reward`, wallet, (walletState) =>
              (walletState.shielded.balances[shieldedToken().raw] ?? 0n) ===
              beforeDelegators[index]! + expected[index]!
                ? walletState
                : false
            )
          )
        );
        const targetState = await waitFor('target execution state', async () => {
          const publicState =
            await beneficiaryTargetProviders.publicDataProvider.queryContractState(targetAddress);
          if (!publicState) return false;
          const current = compositeTargetLedger(publicState.data);
          return current.guaranteedExecutions === 4n ? current : false;
        });
        assert.equal(targetState.fallibleExecutions, 3n);
        return {
          statuses: submissions.map(({ status }) => status),
          rotation: activeEnrollments.map((enrollment) =>
            Buffer.from(enrollmentIdentity(enrollment.payload.nightRewardAddress)).toString('hex')
          ),
          cursor: state.rewardCursor.toString(),
        };
      }
    );

    await scenario('authenticated service removal compacts the live queue', async () => {
      const identity = Buffer.from(
        enrollmentIdentity(activeEnrollments[1]!.payload.nightRewardAddress)
      ).toString('hex');
      const removed = await fetch(`${baseUrl}/v1/admin/delegators/${identity}`, {
        method: 'DELETE',
        headers: { authorization: `Bearer ${serviceConfig.adminToken}` },
      });
      assert.equal(removed.status, 204);
      const state = await waitFor('delegator removal', async () => {
        const current = await deployedSentinel.readState();
        return current.delegatorCount === 2n ? current : false;
      });
      assert(!state.delegatorPositions.member(Uint8Array.from(Buffer.from(identity, 'hex'))));
      return {
        delegatorCount: state.delegatorCount.toString(),
        cursor: state.rewardCursor.toString(),
      };
    });

    await scenario('finalized deregistration causes automatic stale-entry removal', async () => {
      report.transactions.deregisterSelected = await deregisterNight(eligible[2]!);
      const staleIdentity = enrollmentIdentity(activeEnrollments[2]!.payload.nightRewardAddress);
      const state = await waitFor('stale delegator removal', async () => {
        const current = await deployedSentinel.readState();
        return current.delegatorCount === 1n ? current : false;
      });
      assert(!state.delegatorPositions.member(staleIdentity));
      return {
        removedIdentity: Buffer.from(staleIdentity).toString('hex'),
        delegatorCount: state.delegatorCount.toString(),
      };
    });

    const finalPublic =
      await beneficiarySentinelProviders.publicDataProvider.queryContractState(sentinelAddress);
    assert(finalPublic);
    const finalState = sentinelLedger(finalPublic.data);
    report.final = {
      finalizedBlock: await graphql('{ block { height } }'),
      delegatorCount: finalState.delegatorCount.toString(),
      rewardCursor: finalState.rewardCursor.toString(),
      sponsorshipPurchases: finalState.sponsorshipPurchases.toString(),
      receiptCount: finalState.sponsorshipReceipts.size().toString(),
    };
    report.verdict = 'confirmed';
    report.stage = 'complete';
    report.finishedAt = new Date().toISOString();
    await writeFile(reportPath, JSON.stringify(report, null, 2), { mode: 0o600 });
    console.log(JSON.stringify({ devnetE2E: 'confirmed', reportPath, report }));
  } catch (error) {
    report.verdict = report.baseline === undefined ? 'inconclusive-devnet-unavailable' : 'failed';
    report.finishedAt = new Date().toISOString();
    report.error = error instanceof Error ? (error.stack ?? error.message) : String(error);
    await writeFile(reportPath, JSON.stringify(report, null, 2), { mode: 0o600 });
    console.error(JSON.stringify({ devnetE2E: report.verdict, reportPath, error: report.error }));
    process.exitCode = 1;
  } finally {
    if (service) await service.stop();
    if (server) await server.close();
    database?.close();
    await Promise.allSettled(wallets.map(({ wallet }) => wallet.stop()));
  }
};

await main();
